### ISSUE TITLE
Question about the License

### ISSUE THREAD

**Issue by kaaimon** [chenglei1986/NavigationBar#1]
I think it is very nice library.  
I want use it but not found license.  
Would you tell me about this?  

Thanks.

**Comment by chenglei1986** [comment]
Thanks for reminding. 

I've already added a [license](https://github.com/chenglei1986/NavigationBar/blob/master/README.md).

**Comment by kaaimon** [comment]
Thank you for added a license.
I was able to make app like iOS UI.
